### ISSUE TITLE
Development stalled since July 2015?

### ISSUE THREAD

**Issue by jensens** [authomatic/authomatic#135]
Looks like the development stalled since July 15. @peterhudec if you need any help please tell us, there are some people out there using authomatic! Its great - but it needs some updates.

**Comment by olivierpons** [comment]
+1 I'm eagerly waiting to test it on Python 3 because I'd like to go to python 3 and Django 1.9. Right now I cant...

**Comment by jensens** [comment]
Update: Some time ago I wrote @peterhudec a pm and he answered that he had no time for personal reasons and will look how to improve the situation i.e by adding maintainers. Stay tuned.

**Comment by touilleMan** [comment]
@olivierpons I'm using Authomatic with Python3 in production for more than a year, it works great (at least for OAuth2 with Github, Google and Facebook providers), what trouble do you have ?

**Comment by olivierpons** [comment]
Hi,

I do not have a problem with Python3 because.. I backported all my Django
1.8 to python 2 to be able to run Authomatic. I didnt see there was a
Python3 compatible version, so now everything is made for Django 1.8/Python
2 version...
​

**Comment by mrichar1** [comment]
Just bumping this issue - I've just discovered authomatic, only to find it's very close to, but not quite working, mostly due to outstanding PRs needing applied.

Does anyone have a handle on whether or not there is progress on devolving access? Or is there scope to re-focus effort around a different fork?

**Comment by jensens** [comment]
If there is no motion in here: As an alternative, we can create an organization (i.e. ``authomatic`` and fork it there in order to create a community/collectively managed project under a slightly different name (i.e. ``authomatic-collective``) using the same Python namespace. There several people with motivation to help are getting write access. It's the same approach PIL/Pillow took successfully. A later reunion is always possible. 

Who would be interested in participating? If there are 3 or more in here who are raising hand I can take the time to do the management part on Github. I want do Python 3 porting but can do reviews on Pull Request (PRs). 

We should apply minimal rules, like that a PR needs a positive review and green tests before merging, no commits on master (protected branch) and PRs are merged by a different person than the submitter. I would also like to see semantic versioning applied.

**Comment by touilleMan** [comment]
@jensens we should try to reach @peterhudec before doing a fork (given his github&twitter accounts still show recent activity)
The best would be he creates the organization and [automate the release on pypi with travis](https://docs.travis-ci.com/user/deployment/pypi/).

I propose we wait for his answer about a week, then try to contact him on twitter, then go for the fork

> We should apply minimal rules, like that a PR needs a positive review and green tests before merging, no commits on master (protected branch) and PRs are merged by a different person than the submitter. I would also like to see semantic versioning applied.

:+1:

**Comment by olivierpons** [comment]
I've already done my own port for Python 3 and my website about my keyboard (a project stopped right now) https://www.ergofip.com is using Python 3.6 and my custom port of authomatic. I'm not the best with Python so I dont know if my code is "pythonic" or not, but I can share it and you can merge it (or something like that).

**Comment by mrichar1** [comment]
As has been suggested, doing this with the original author's support would allow for a much easier migration. I'm happy to volunteer myself for some of this migration work. I'm (mostly) a python developer, and have a bit of experience in helping run community projects. I'd be mostly interested in helping facilitate project involvement, getting bugs closed and PRs accepted, etc rather than being any kind of lead developer or benevolent dictator :smiley: 

I'd suggest an approach along the following lines:

1. Migrate to community project, add admins, automate things like pypi updates etc.
2. 'Standardisation' - py3x compatability, pep8/pylint, etc. (All subsequently tested for via travis).
3. Bug backlog - try to get all bugs highlighted in issues/PRs resolved.
4. Features overview/project direction - review the project at this point to see if there are any high-level changes that need making. Review any issues/PRs which define/describe new features and see if they fit.

1 and 2 are pretty much mandatory for authomatic to be more community-driven - 3 is required to keep it as a useful project, and 4 would also be great, but will depend on how much community involvement there ends up being.

**Comment by peterhudec** [comment]
Hi guys,

First of all, thank you for you support, and my apologies for neglecting the project.

The thing is that since I moved to London, I haven't been able to find energy to take care for my side projects. I made several attempts to bring Authomatic back to life, but first I needed to update its development dependencies [liveandletdie](https://github.com/peterhudec/liveandletdie) and [chromedriver-installer](https://github.com/peterhudec/chromedriver_installer) (the [foundation-sphinx-theme](https://github.com/peterhudec/foundation-sphinx-theme) deserves an update as well).

I had big plans for the project, I wanted to:

* Fix the proxy related issues.
* Cover everything with unit tests.
* Add CI hooks including a linter and test coverage.
* Rewrite the way the provider IDs are managed (write a meta class to keep track of the IDs).
* Make the JavaScript part UMD compatible.
* Add [OpenID Connect](http://openid.net/connect/) support.
* Add support for all Python web frameworks.
* Implement a script for simplifying addition of new providers.

But I have to admit that it's not realistic for me to even address all the PRs.

I think it's about the time to pass the project and its management on to the community and resolving this very issue seems to be the first step towards this goal.

I think the next steps for me should be to create an organization (I suggest the name "authomatic" but I'm open to suggestions) and add @jensens, @touilleMan and @mrichar1 as administrators if you  guys don't mind. I'm not sure though how to transfer all the issues and pull requests.

Let me know your thoughts.

**Comment by jensens** [comment]
@peterhudec thanks for speaking up and also for welcoming the idea of the community-driven approach! 

I think ``authomatic`` as a name for the organization is obvious and fine. I am ok to act as maintainer, even if I won't be the person writing much code.

The easiest way to get the repository with all PRs over to the new home is a ``transfer`` (under settings in the red danger zone. The disadvantage is, every direct clone of this repository would need a git remote add (or edit of ``.git-config``). I do not now how forks are addressed but for local clones, it's probably the same and inside Github, it should work automatically.

**Comment by mrichar1** [comment]
That sounds great - thanks for starting off this project and then passing it on now it's grown arms and legs!

Happy to be involved in it's ongoing development!

**Comment by touilleMan** [comment]
> The easiest way to get the repository with all PRs over to the new home is a transfer (under settings in the red danger zone). The disadvantage is, every direct clone of this repository would need a git remote add (or edit of .git-config). I do not now how forks are addressed but for local clones, it's probably the same and inside Github, it should work automatically.

I think Github keep track of original owner and do the redirection by itself is long as it is possible (i.e. `github.com/peterhudec/authomatic` would redirect to `github.com/authomatic/authomatic` until @peterhudec recreate a personal project named `authomatic`, or fork `authomatic/authomatic`)

**Comment by mrichar1** [comment]
Thanks to @peterhudec for moving the project across to being an organization!

I've done a couple of small things so far to help us begin the necessary work:

1. updated the README to fix some links, and added a short 'update; paragraph explaining that work is ongoing. (Hopefully the only time I'll make a direct commit to the master branch!)

2. Created #authomatic IRC channel on chat.freenode.net - to give us a starting place to discuss things (we can then decide on how best to communicate and choose something else if necessary).

3. Added some basic tags to all PRs - to try to categorise them into bugs versus enhancements, and separate them according to whether they relate to openid, oauth1/2, documentation or core.

Looking forward to chatting with you all about this soon!

**Comment by jensens** [comment]
Thanks! I think we now can close this!
