### ISSUE TITLE
Deprecate this project?

### ISSUE THREAD

**Issue by jeffoneill** [authomatic/authomatic#196]
I've used Authomatic for many years, and have really appreciated all the work people have put into it, but it seems that it is not keeping up with the times.  The three most popular providers don't or soon won't work out of the box:

- Google (G+ being retired)
- Facebook (need to manually update API version)
- Microsoft (very out of date and doesn't work)

I've switched one of my projects to Flask-Dance and will soon migrate another to something else.

I don't want to be too negative, but at this point, it seems best to update the official docs to suggest that people use other software for their Oauth needs.

**Comment by ergo** [comment]
There are discussions in #192 I think we probably need to step in and maintain the project or make a friendly fork with hope we can mege changes back in when @peterhudec decides he wants our changes.
CC @marcinkuzminski

**Comment by fmigneault** [comment]
@ergo @peterhudec 
I'm also interested in keeping using Authomatic for [Magpie](https://github.com/Ouranosinc/Magpie), but unfortunately even my somewhat recent PR #195 remains unused...
I've kept using my fork https://github.com/fmigneault/authomatic/tree/httplib-port in my requirements for a long time.
Open in helping out in this effort as needed.

**Comment by mrichar1** [comment]
The work done leading up to #192 was pretty successful in clearing through a lot of PRs and issues, but it became stuck at the lack of a release - in part due to the issue that the functional tests are now mostly broken - partly because the oauth providers have changed/gone away, and partly because the project in turn relies on other libraries which in turn are out of maintenance (specifically the ones pulled into the organisation: https://github.com/authomatic)

There are a small number of us who were added to the organisation who have access to do the required work - i.e merge PRs, make releases etc - so a full fork isn't necessarily required - however since we're not the original/main developers, we've all I think held back from making those kinds of 'big decisions' (I can't comment on how much time or effort anyone else has to contribute to this). Perhaps this needs to change (ideally with @peterhudec's blessing of course!)

I think we really only have 3 options moving forward:

1. Deprecate/abandon the project.
2. Drop the functional/e2e tests, continue with just unit tests.
3. Get all of the tests working before continuing.

I think right now, 2 is the best option - assuming the unit tests and codebase are salveagable in their curent state without a ton of man hours (and @fmigneault's latest PR implies it is doable). 

3 would be amazing, but requires a *lot* of work to fix multiple libraries, (re)learn the oauth providers, and fix up the code base to match. 

1 is of course the 'default' position but I believe there's still enough interest and motivation to try to avoid that happening if possible!

So, I'd like to propose the following:

1. Review functional tests, and remove any which are broken and not easily fixable.
2. Have another round of working through PRs and Issues to get a stable code base.
3. Make a new release.

I'm also open to adding new people to the organisation to help with the above (i.e. @fmigneault)

Thoughts? (especially @peterhudec, @ergo, @jensens...)

**Comment by ergo** [comment]
I think we need to get simplified tests working, by any means necessary. We can start with few few ones that work and are the most used ones - google, facebook. Once this is tackled merging in PR's fixing the rest should be considerably easier. I'm reluctant to merge in anything without working tests.

**Comment by jensens** [comment]
+1 for simplifying tests. The current test suite is complex and so itself fragile, which is against the intention of testing.

also +1 for adding more people to the project. I have some good experience with other FOSS projects maintained by lots of people, as long as there is some steering.

**Comment by ergo** [comment]
Lets discuss this in authomatic slack channels :)

**Comment by robinharms** [comment]
I'd like to help too if there's anything special you need. I'd really like to see a new release.

Supporting all of the different frameworks out of the box also seems like it might be an overreach. It's already quite easy to add provider classes yourself. That would solve stuff like outdated links.

**Comment by mrichar1** [comment]
There's actually been some movement behind the scenes - we've managed to strip things back in #198 and get the test suite going again, with a small set of 'big' providers (currently facebook and github (oauth2), and twitter almost ready (oauth1)).

I hope by the end of next week that I'll have the extra providers working, and will merge this PR.

Once that's done, we can make a new release.  After that, we can revisit existing PRs and see which are passing/failing the updated tests.

**Comment by mrichar1** [comment]
OK! It's done! :open_mouth: 

`master` is now passing tests against `facebook`, `github`  (both `oauth2`) and `twitter` (`oauth1`).

Outstanding PRs will need to have `master` merged in, which (assuming no conflicts) should kick off `travis` - that will then let us be able to better decide if they are save to merge into `master`.

Let the updating commence! :grinning:

**Comment by ergo** [comment]
Great work @mrichar1 !

**Comment by jensens** [comment]
I think, after @mrichar1 amazing work we can now continue developing and releasing Authomatic. So, I close this issue.
