### ISSUE TITLE
Need support for Facebook API v2.0 and v2.1

### ISSUE THREAD

**Issue by mgoldwasser** [authomatic/authomatic#61]
Would it be possible to add support for Facebook API v2.0 and v2.1? It looks like Facebook v1.0 will no longer be supported after April 30th 2015:
https://developers.facebook.com/docs/facebook-login/v2.1

**Comment by brephophagist** [comment]
I have been monkeypatching with something like [this](https://gist.github.com/brephophagist/2094a056bd08b835b2eb). The "reauth" thing is just to get an extra GET param into the requests sent to FB, if you need to re-request permissions (because the user killed some of them in the itemized dialog Facebook now provides).

Not claiming it's great code, but hope it helps someone.

**Comment by mgoldwasser** [comment]
@brephophagist thanks - I think there is still a bug however, because Facebook now does not grant you access to the username, so the picture url as generated by authomatic will be broken.

I have tried to address these changes in my pull request here:
https://github.com/peterhudec/authomatic/pull/96

**Comment by mrichar1** [comment]
Resolved in #164
