### ISSUE TITLE
Redirecting user to the original referring URL after a successful login

### ISSUE THREAD

**Issue by fabito** [authomatic/authomatic#70]
We are using the Google provider and we need to redirect the user to the original referring url after login.
I was thinking about encoding extra data in the state parameter but Authomatic doesn't seem to provide any API for that. Also thought about storing the referer (from the request header) in the session.
Any recommendation on how to do that ? 

thanks in advance 
Fábio

**Comment by martin-sucha** [comment]
One use case I see where allowing the user of the library to add information to the OAuth 2.0 state parameter is when you are opening multiple browser tabs with different URLs in the application at the same time (such as when you have multiple homepages set in your browser or someone sends you a list of links to view and you open them all at once).

Without custom state, you can only remeber the last referrer URL in the session, so when you have multiple browser tabs opening at the same time, you may well end up opening a single page that wins the race of storing the URL in the session. Therefore I suggest adding an option to append an arbitrary user provided string to the OAuth2 state parameter that would be returned in the login result to distinguish the tab that is being opened. The library would just concat the user provided string with the CSRF token and return the portion after CSRF token in the LoginResult. Verifying and handling of the custom state string would be left for the user. Since the length of the CSRF token is fixed, it can be easily extracted from the string for verification purposes (in case of variable length tokens, a length would have to be stored in the state as well).

Sure, you have to use the session as a fallback anyway if you use non-OAuth-2.0 providers, but some people, including me, don't use those.

I think the patch to Authomatic will be small and I'm willing to implement it if we agree on the API. An example of how this could be used:

```python
def state():
    """called in Phase 1 when the provider generates the OAuth 2.0 state.
    The return value of this function will be appended to the generated CSRF token.
    """
    return sign(self.request.headers.get('referer', '/'), secret)
    # alternatively, you can store this in session if you don't mind polluting it with keys
    # you may not be able to remove:
    # key = 'redirect_{}'.format(self.session.get('counter', 0) + 1)
    # self.session[key] = self.request.headers.get('referer', '/')
    # return key

result = authomatic.login(WerkzeugAdapter(request, response), provider_name, state=state)
if result:
    # Phase 2
    if result.state and verify_signature(result.state):
        redirect_url = url_from_state(result.state)
    else:
        redirect_url = self.session['redirect_to']
    # Process login and redirect
else:
    # Phase 1
    referer = self.request.headers.get('referer', '/')
    self.session['redirect_to'] = referer
```

What do you think about such an addition?

**Comment by dirkmoors** [comment]
+1

I'm having a similar issue with Django

Consider the view:

```python
@login_required()
def secret_page(request):
    return HttpResponse('Super secret! The user must be logged in!')
```

When I go that view, Django redirects me to '...../auth/login/?next=/secret_page/'.
And also in this case, having params prevents stage 1 of the OAuth Flow from starting....

Is there a solution in the making for this?

**Comment by ParthGandhi** [comment]
@martin-sucha +1

I think `state` is the superior solution for pretty much the reasons you mention. However, since OAuth1 does not support it, the API can instead take in a `callback_url` that internally gets transformed to the right version i.e. using `state` for OAuth2 and `oauth_callback` for OAuth1 (though i'm not sure *all* OAuth1 providers support the callback - at least Twitter does, and I suspect most others do as well).

I've hacked together working versions of these (so theres at least a POC), but its not good enough for a PR.
